#!/usr/bin/env python3
"""Codex job 08. Claim: directly build the one-factor cone and Candidate 1.
Cases: two seeded primitive triples in GF(2^16); Ext at most degree 3.
Conventions: left modules, column matrices; R(b) means right multiplication
by b; characteristic two. Every linear solve has at most 100000 unknowns.
Computed claims have status supported in the recorded cases only.
"""
import os, sys, json, random, time, hashlib
from pathlib import Path
HERE=Path(__file__).resolve().parent
os.environ['DOT_SAGE']=str(HERE/'sage-state')
sys.dont_write_bytecode=True
sys.path.insert(0,str(HERE.parent/'02-ar-finite-data'))
from importlib import import_module
base=import_module('01_algebra'); te=import_module('04_trivial_extension')
coc=import_module('05_cochain')
from sage.all import GF, matrix, vector, VectorSpace, identity_matrix, block_diagonal_matrix, gcd, save, load
import faulthandler
faulthandler.dump_traceback_later(60,repeat=True)
LIMIT=100000
START=time.time()
SYSTEMS=[]
def emit(*x): print(round(time.time()-START,2),*x,flush=True)
def guard(name,rows,cols):
    SYSTEMS.append({'name':name,'equations':int(rows),'unknowns_per_rhs':int(cols)})
    if cols>LIMIT: raise BoundStop(SYSTEMS[-1])
class BoundStop(Exception): pass

def kernel(M,name):
    guard(name,M.nrows(),M.ncols())
    return M.right_kernel_matrix().transpose()
def section_columns(B):
    """Left inverse of a full column rank inclusion, using pivot rows."""
    piv=list(B.transpose().pivots()); S=B.matrix_from_rows(piv)
    guard('inclusion coordinates',S.nrows(),S.ncols())
    return piv,S.inverse()
def restrict(acts,B,name):
    piv,inv=section_columns(B); ans=[]
    for a in acts:
        C=a*B; D=inv*C.matrix_from_rows(piv)
        assert B*D==C,(name,'invariance')
        ans.append(D)
    return ans

def quotient(acts,B,name):
    """Quotient by column span B, with canonical complement from echelon pivots."""
    K=B.base_ring(); n=B.nrows(); B=B.column_space().basis_matrix().transpose()
    piv=list(B.transpose().pivots()); free=[i for i in range(n) if i not in piv]
    S=identity_matrix(K,n).matrix_from_columns(free)
    Q=identity_matrix(K,n).matrix_from_rows(free)
    if piv: Q-=B.matrix_from_rows(free)*identity_matrix(K,n).matrix_from_rows(piv)
    assert Q*B==0 and Q*S==identity_matrix(K,len(free))
    out=[]
    for a in acts:
        b=Q*a*S; assert Q*a==b*Q,(name,'quotient linearity'); out.append(b)
    return out,Q,S

class Bimodules:
    def __init__(self,T):
        self.T,self.K=T,T.K; K=self.K
        self.mu=[[{k:v for k,v in enumerate(x) if v} for x in row] for row in T.table]
        self.gens=[T.names.index(x) for x in 'xutZ']
        # Verify these really generate T as an algebra.
        V=VectorSpace(K,20); S=V.subspace([T.b('e'),T.b('f')])
        while True:
            D=V.subspace(list(S.basis())+[T.mul(T.basis[a],b) for a in self.gens for b in S.basis()])
            if D==S: break
            S=D
        assert S.dimension()==20
        self.ag=self.gens+[20+a for a in self.gens]
        self.verts=[('e','e'),('e','f'),('f','e'),('f','f')]
        self.ids=[]; self.indecs=[]
        for l,r in self.verts:
            pairs=[(a,b) for a in range(20) for b in range(20) if T.corners[a][1]==l and T.corners[b][0]==r]
            self.ids.append(pairs); ix={p:i for i,p in enumerate(pairs)}; acts=[]
            for k in range(40):
                entries={}
                for j,(a,b) in enumerate(pairs):
                    terms=self.mu[k][a] if k<20 else self.mu[b][k-20]
                    for c,v in terms.items(): entries[ix[(c,b) if k<20 else (a,c)],j]=v
                acts.append(matrix(K,len(pairs),len(pairs),entries,sparse=True))
            self.indecs.append(acts)
    def regular(self,H=None):
        K=self.K; acts=[]
        for k in range(40):
            acts.append(matrix(K,20,20,{(c,b):v*(H if H is not None and k>=30 else 1)
                for b in range(20) for c,v in (self.mu[k][b] if k<20 else self.mu[b][k-20]).items()},sparse=False))
        return acts
    def projective(self,vs):
        acts=[block_diagonal_matrix([self.indecs[v][a] for v in vs],sparse=True) for a in range(40)]
        starts=[]; n=0
        for v in vs:
            l,r=self.verts[v]; starts.append(n+self.ids[v].index((self.T.names.index(l),self.T.names.index(r))))
            n+=len(self.ids[v])
        return {'acts':acts,'vertices':vs,'starts':starts,'dim':n}
    def cover(self,M,label):
        K=self.K; n=M[0].nrows(); V=VectorSpace(K,n)
        emit(label,'start radical',n)
        # Radical generated by the checked algebra generators on either side.
        RR=matrix(K,[c for a in self.ag for c in M[a].columns()])
        guard(label+' radical equations',RR.nrows(),RR.ncols())
        emit(label,'radical matrix',RR.dimensions())
        radbasis=RR.row_space().basis_matrix().transpose()
        current=radbasis; vs=[]; gs=[]
        emit(label,'radical rank',radbasis.ncols())
        for v,(l,r) in enumerate(self.verts):
            E=M[self.T.names.index(l)]*M[20+self.T.names.index(r)]
            joined=current.augment(E)
            piv=list(joined.pivots())
            selected=[j-current.ncols() for j in piv if j>=current.ncols()]
            gs.extend(E.column(j) for j in selected); vs.extend([v]*len(selected))
            current=joined.matrix_from_columns(piv)
        assert current.ncols()==n
        emit(label,'top selected',vs, 'constructing projective')
        P=self.projective(vs)
        ep=matrix(K,[M[a]*(M[20+b]*g) for v,g in zip(vs,gs) for a,b in self.ids[v]]).transpose()
        emit(label,'cover matrix built',ep.dimensions())
        assert ep.rank()==n
        assert all(ep*P['acts'][a]==M[a]*ep for a in range(40))
        B=kernel(ep,label+' cover kernel')
        # Minimality: chosen generators are a basis of the radical quotient.
        assert len(gs)==n-radbasis.ncols()
        syz=restrict(P['acts'],B,label)
        emit(label,'dim',n,'top',[vs.count(v) for v in range(4)],'P',P['dim'],'kernel',B.ncols())
        return P,ep,B,syz

# Sparse relative normalised bars: tuple (left, inner letters..., right).
def plus(d,k,c):
    if not c: return
    v=d.get(k,0)+c
    if v: d[k]=v
    else: d.pop(k,None)
def add(d,s,c):
    for w,v in s.items(): plus(d,w,c*v)
def bar_action(B,s,a,b):
    out={}
    for w,c in s.items():
        for l,x in B.mu[a][w[0]].items():
            for r,y in B.mu[w[-1]][b].items(): plus(out,(l,)+w[1:-1]+(r,),c*x*y)
    return out
def contract(B,s):
    out={}
    for w,c in s.items():
        if w[0] not in [0,8]: plus(out,(B.T.names.index(B.T.corners[w[0]][0]),)+w,c)
    return out
def bd(B,s):
    out={}
    for w,c in s.items():
        for j in range(len(w)-1):
            for a,x in B.mu[w[j]][w[j+1]].items():
                # Internal products are radical; outer terms allow idempotents.
                plus(out,w[:j]+(a,)+w[j+2:],c*x)
    return out
def combine(images,v):
    out={}
    for j in v.nonzero_positions(): add(out,images[j],v[j])
    return out
def comparison(B,P,previous,d):
    images=[]
    for v,start in zip(P['vertices'],P['starts']):
        target=combine(previous,d.column(start)); lift=contract(B,target)
        assert bd(B,lift)==target
        for a,b in B.ids[v]: images.append(bar_action(B,lift,a,b))
    assert len(images)==P['dim']
    for j,s in enumerate(images): assert bd(B,s)==combine(previous,d.column(j))
    emit('bar comparison','degree',len(next(iter(next(s for s in images if s))))-2,'vectors',len(images),'terms',sum(map(len,images)))
    return images

def build_cone(B,records):
    M=B.regular(); Ps=[]; ds=[]; inclusions=[]; prev=None
    for a in range(3):
        P,ep,inc,M=B.cover(M,'bimodule degree '+str(a))
        d=ep if a==0 else prev*ep
        Ps.append(P); ds.append(d); inclusions.append(inc); prev=inc
        records.append({'a':a,'P':P['dim'],'syzygy':ep.nrows(),'next_syzygy':inc.ncols(),'betti':[P['vertices'].count(v) for v in range(4)]})
        if a: assert ds[a-1]*d==0
    # Minimal degree-zero cover identified with the relative bar degree zero.
    images0=[{(a,b):B.K(1)} for v in Ps[0]['vertices'] for a,b in B.ids[v]]
    assert all(B.T.mul(B.T.basis[a],B.T.basis[b])==ds[0].column(j) for j,s in enumerate(images0) for a,b in s)
    images1=comparison(B,Ps[1],images0,ds[1]); images2=comparison(B,Ps[2],images1,ds[2])
    _,_,p,_=coc.setup(B.K,B.T.q,coc.read_entries())
    cols=[]
    for k in inclusions[2].columns():
        cycle=combine(images2,k); assert not bd(B,cycle)
        lift=contract(B,cycle); assert bd(B,lift)==cycle
        val=vector(B.K,20)
        for w,c in lift.items():
            assert len(w)==5
            for x,v in p.get(w[1:-1],{}).items():
                val+=c*v*B.T.mul(B.T.mul(B.T.basis[w[0]],B.T.basis[x]),B.T.basis[w[-1]])
        cols.append(val)
    tau=matrix(B.K,cols).transpose()
    regular=B.regular()
    assert all(tau*M[a]==regular[a]*tau for a in range(40))
    emit('tau on Omega3','shape',tau.dimensions(),'rank',tau.rank(),'all bimodule identities PASS')
    acts=[block_diagonal_matrix([regular[a],Ps[2]['acts'][a]],sparse=False) for a in range(40)]
    relation=tau.stack(inclusions[2])
    C,Q,S=quotient(acts,relation,'cone pushout')
    emit('cone C dimension',C[0].nrows())
    return C,{'Ps':Ps,'ds':ds,'inc':inclusions,'tau':tau,'quotient':Q,'section':S}

def main():
    case=int(sys.argv[1]) if len(sys.argv)>1 else 0
    K=GF(2**16,name='b'); b=K.multiplicative_generator(); rng=random.Random(8082026+case)
    exps=[]
    while len(exps)<3:
        e=rng.randrange(1,65535)
        if gcd(e,65535)==1 and e not in exps: exps.append(e)
    q,H1,H2=[b**e for e in exps]
    result={'job':'Codex job 08','case':case,'status':'running','field':str(K),'modulus':str(K.modulus()),'primitive':str(b),'seed':8082026+case,'exponents':exps,'orders':[int(x.multiplicative_order()) for x in [q,H1,H2]],'ratio_order':int((H1/H2).multiplicative_order()),'resolution':[]}
    def record():
        result['systems']=SYSTEMS; result['elapsed_seconds']=time.time()-START
        (HERE/f'case-{case}.json').write_text(json.dumps(result,indent=2,default=str)+'\n')
    record(); emit('parameters',result)
    try:
        base.audit(K,q); T=te.TrivialExtension(K,q); te.structural(T)
        coc.cocycle(K,q,coc.read_entries()); coc.boundary(K,q,H1,coc.read_entries()); coc.boundary(K,q,H2,coc.read_entries()); coc.evaluation(K,q,coc.read_entries())
        B=Bimodules(T); C,data=build_cone(B,result['resolution']); result['dim_C']=C[0].nrows(); record()
        save({'C':C,'data':data,'parameters':result},str(HERE/f'cone-{case}.sobj'))
        result['status']='cone constructed; further construction pending'
    except BoundStop as err:
        result['status']='stopped at requested bound'; result['bound']=err.args[0]; emit('BOUND STOP',err.args[0])
    finally: record()
if __name__=='__main__': main()
