#!/usr/bin/env python3
"""Codex job 07: explicit certificates, independent of toda.py's Hom solver.
Claim: the two specified Toda brackets contain zero and have zero indeterminacy.
Cases: F_2(q), primitive q in GF(2^8), GF(2^12), GF(2^16).
Conventions: left modules, columns, stars denote the dual C-basis, [1]=Omega^-1.
Build multiplication afresh from C's listed products and the trivial-extension
definition. Verify the hand formulas on every T-basis/module-basis pair.
Run: python computations/04-toda-bracket/witness.py > computations/04-toda-bracket/witness.out
"""
import os
import sys
from pathlib import Path
HERE=Path(__file__).resolve().parent
os.environ['DOT_SAGE']=str(HERE/'.sage')
sys.dont_write_bytecode=True
from sage.all import GF, PolynomialRing, vector, matrix, VectorSpace


def run(K,q):
    names=list('exyzuvtjfn')
    ix={n:i for i,n in enumerate(names)}
    products={}
    corners=['ee']*4+['ef']*2+['fe']*2+['ff']*2
    for n,(l,r) in zip(names,corners):
        products[l,n]={n:K(1)}; products[n,r]={n:K(1)}
    for a,b,c in [('x','y',{'z':q}),('y','x',{'z':1}),
                  ('x','u',{'v':1}),('y','u',{'v':1}),
                  ('t','x',{'j':1}),('t','y',{'j':q*q}),
                  ('u','t',{'y':1,'x':q}),('v','t',{'z':q}),
                  ('u','j',{'z':1}),('t','u',{'n':1+q}),
                  ('n','t',{'j':q}),('u','n',{'v':1})]:
        products[a,b]={n:K(c0) for n,c0 in c.items()}
    # Three separate contributions c*d, c*psi, phi*d; DC*DC=0.
    def mul(a,b):
        out=vector(K,20)
        for i in range(10):
            for j in range(10):
                for n,c in products.get((names[i],names[j]),{}).items():
                    k=ix[n]
                    out[k]+=a[i]*b[j]*c
                    # (c psi)(d)=psi(d c), (phi d)(c)=phi(d c).
                    out[10+i]+=a[j]*b[10+k]*c
                    out[10+j]+=a[10+k]*b[i]*c
        return out
    B=list(VectorSpace(K,20).basis())
    N=names+[s.upper() for s in names]
    b=lambda n:B[N.index(n)]
    span=lambda vs:VectorSpace(K,20).subspace(vs)
    cols=lambda vs:matrix(K,vs).transpose()
    Pe=span([mul(a,b('e')) for a in B])
    Pf=span([mul(a,b('f')) for a in B])
    M1=cols([b(n) for n in ['u','v','n','T','J','F','N']])
    M2=cols([b('x')+b('y'),b('z'),b('j'),b('E'),b('X')+q*b('Y')])
    M3=cols([b('x')+q*b('y'),b('z'),b('j'),b('E'),b('X')+b('Y'),b('U'),b('V')])
    assert (Pe.dimension(),Pf.dimension())==(12,8)
    assert all(M.rank()==M.ncols() for M in (M1,M2,M3))
    for M in (M1,M2,M3):
        for a in B:
            for v in M.columns():
                assert mul(a,v) in span(M.columns())
    # The first three covers are f-coordinate, right u, right (x+y).
    p0=matrix(K,1,8,[v[ix['f']] for v in Pf.basis()])
    p1=cols([mul(v,b('u')) for v in Pe.basis()])
    p2=cols([mul(v,b('x')+b('y')) for v in Pe.basis()])
    assert p0.rank()==1 and p1.column_space()==span(M1.columns())
    assert p2.column_space()==span(M2.columns())
    assert cols(Pf.basis())*p0.right_kernel().basis_matrix().transpose()==M1
    assert span((cols(Pe.basis())*p1.right_kernel().basis_matrix().transpose()).columns())==span(M2.columns())
    assert span((cols(Pe.basis())*p2.right_kernel().basis_matrix().transpose()).columns())==span(M3.columns())
    # beta0 sends 1 to F. Right U lifts it; right X lifts beta1.
    assert mul(b('U'),b('u'))==b('F')
    assert mul(b('X'),b('x')+b('y'))==b('E')
    beta1=lambda v:v[ix['u']]*b('E')
    beta2=lambda v:v[ix['x']]*b('E')
    for v in M1.columns():
        assert mul(v,b('U'))==beta1(v)
    for v in M2.columns():
        assert mul(v,b('X'))==beta2(v)
    for a in B:
        assert mul(a,b('F'))==a[ix['f']]*b('F')
        for v in M1.columns():
            assert beta1(mul(a,v))==mul(a,beta1(v))
        for v in M2.columns():
            assert beta2(mul(a,v))==mul(a,beta2(v))
    assert beta1(b('F'))==0
    assert all(beta2(beta1(v))==0 for v in M1.columns())
    tau=lambda v:v[10+ix['v']]
    assert tau(b('V'))==1
    for a in B:
        for v in M3.columns():
            assert tau(mul(a,v))==a[ix['f']]*tau(v)
    assert all(tau(beta2(v))==0 for v in M2.columns())
    # Cone(tau) = Te/W, W=ker(tau|M3); s embeds as [V].
    W=span(M3.columns()[:-1])
    assert W.dimension()==6 and b('V') not in W
    lift=lambda v:v[ix['u']]*b('X')
    for a in B:
        for v in M1.columns():
            assert lift(mul(a,v))-mul(a,lift(v)) in W
    for v in M1.columns():
        assert mul(lift(v),b('x')+b('y'))==beta1(v)
    assert lift(b('F'))==0
    # Indeterminacy groups: M1 is generated by u, so Hom(M1,s)=0;
    # a possible s -> M3 lands in <j,U,V>, and left u is injective there.
    assert span([mul(a,b('u')) for a in B])==span(M1.columns())
    fpart=span([mul(b('f'),v) for v in M3.columns()])
    assert fpart==span([b('j'),b('U'),b('V')])
    assert span([mul(b('u'),v) for v in fpart.basis()]).dimension()==3
    # beta cone: (M1 + Pf)/<(F,F)>; G(m,p)=beta1(m) is well-defined
    # and T-linear by the preceding exhaustive checks; beta2*G=0 literally.
    print('FIELD',K,'q=',q,flush=True)
    if K.is_finite():
        print('modulus',K.modulus(),'order',q.multiplicative_order(),flush=True)
    print('PASS: explicit syzygy bases, right-U/right-X lifts, all linearity identities')
    print('PASS: Cone(tau)=Te/<x+qy,z,j,E,X+Y,U>; lift(u)=[X], lift(F)=0')
    print('PASS: beta cone extension G(m,p)=beta1(m); beta2 G=0')
    print('PASS: H^1=H^-3=0 by cyclicity and injective left-u on fM3')
    print('RESULT: both Toda brackets are {0}; c=0 (exact certificates)',flush=True)


if __name__=='__main__':
    K=PolynomialRing(GF(2),'q').fraction_field()
    run(K,K.gen())
    for n in [8,12,16]:
        K=GF(2**n,name='a')
        run(K,K.multiplicative_generator())
