/-
Copyright (c) 2026 The findim counterexample formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The findim counterexample formalisation contributors
-/
import FindimCounterexample.FiniteQuotients
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.BigOperators.Pi
import Mathlib.Algebra.Group.TypeTags.Hom

/-!
# The finite central subgroups in the matrix quotients

The coordinate vectors generate the multiplicative form of a finite product
of additive groups `ZMod 2`. Transport through the quotient-ring power basis
and the central transvection identifies this group with the subgroup generated
by the first `m` images of the central involutions.
-/

noncomputable section

namespace FindimCounterexample.FiniteQuotients

open scoped BigOperators

/-- The elementary abelian coordinate group for a quotient of period m. -/
abbrev Coordinates (m : ℕ) := Multiplicative (Fin m → ZMod 2)

/-- The coordinate vector with a single nonzero entry, written multiplicatively. -/
def coordinateGenerator {m : ℕ} (q : Fin m) : Coordinates m :=
  Multiplicative.ofAdd (Pi.single q 1)

private theorem zmod_two_cases : ∀ a : ZMod 2, a = 0 ∨ a = 1 := by
  decide

/-- The standard coordinate vectors generate the full elementary abelian group. -/
theorem coordinateGenerators_closure (m : ℕ) :
    Subgroup.closure (Set.range (coordinateGenerator (m := m))) = ⊤ := by
  apply top_unique
  intro c _
  change Multiplicative.ofAdd c.toAdd ∈ _
  rw [← Finset.univ_sum_single c.toAdd, ofAdd_sum]
  apply Subgroup.prod_mem
  intro q _
  rcases zmod_two_cases (c.toAdd q) with hq | hq
  · rw [hq, Pi.single_zero]
    exact Subgroup.one_mem _
  · rw [hq]
    exact Subgroup.subset_closure ⟨q, rfl⟩

/-- The range of a homomorphism from the coordinate group is generated by its
values on the standard coordinate vectors. -/
theorem range_eq_closure_coordinates {m : ℕ} {H : Type*} [Group H]
    (f : Coordinates m →* H) :
    f.range = Subgroup.closure (Set.range (fun q => f (coordinateGenerator q))) := by
  rw [MonoidHom.range_eq_map, ← coordinateGenerators_closure m, MonoidHom.map_closure,
    ← Set.range_comp']

/-- A central involution maps into the centre of the image of every
homomorphism from the selection group. -/
theorem z_mem_center_range {H : Type*} [Group H]
    (f : SelectionGroup.G →* H) (N : ℤ) :
    f.rangeRestrict (SelectionGroup.z N) ∈ Subgroup.center f.range := by
  apply Subgroup.mem_center_iff.mpr
  rintro ⟨x, y, rfl⟩
  apply Subtype.ext
  change f y * f (SelectionGroup.z N) = f (SelectionGroup.z N) * f y
  simpa only [map_mul] using
    congrArg f (Subgroup.mem_center_iff.mp (SelectionGroup.z_mem_center N) y)

variable (m : ℕ) (hm : 0 < m)

/-- Coordinate vectors map to top-right transvections through the quotient-ring
power basis. -/
def ambientCoordinates : Coordinates m →* MatGroup m :=
  (MatrixTransvections.eHom (0 : Fin 5) 4 (by decide)).comp
    (FiniteQuotientRing.linearCombination m hm).toAddEquiv.toAddMonoidHom.toMultiplicative

/-- The coordinate map has the prescribed linear-combination coefficient. -/
theorem ambientCoordinates_apply (c : Coordinates m) :
    ambientCoordinates m hm c = MatrixTransvections.e 0 4 (by decide)
      (∑ q : Fin m, c.toAdd q • FiniteQuotientRing.tPow m hm (q.val : ℤ)) := by
  change MatrixTransvections.e 0 4 (by decide)
    (FiniteQuotientRing.linearCombination m hm c.toAdd) = _
  rw [FiniteQuotientRing.linearCombination_apply]

/-- Linear independence of the powers and the top-right matrix entry imply
injectivity of the coordinate map. -/
theorem ambientCoordinates_injective : Function.Injective (ambientCoordinates m hm) := by
  intro a b hab
  apply Multiplicative.toAdd.injective
  apply (FiniteQuotientRing.linearCombination m hm).injective
  exact MatrixTransvections.e_injective 0 4 (by decide) hab

/-- A standard coordinate generator maps to the corresponding central involution. -/
@[simp]
theorem ambientCoordinates_generator (q : Fin m) :
    ambientCoordinates m hm (coordinateGenerator q) = pi m hm (SelectionGroup.z (q.val : ℤ)) := by
  rw [pi_z]
  change MatrixTransvections.e 0 4 (by decide)
    (FiniteQuotientRing.linearCombination m hm (Pi.single q 1)) = _
  rw [FiniteQuotientRing.linearCombination_single]

/-- Every coordinate transvection belongs to the actual image of the selection group. -/
theorem ambientCoordinates_range_le : (ambientCoordinates m hm).range ≤ F m hm := by
  rw [range_eq_closure_coordinates]
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨q, rfl⟩
  change ambientCoordinates m hm (coordinateGenerator q) ∈ F m hm
  rw [ambientCoordinates_generator]
  exact ⟨SelectionGroup.z (q.val : ℤ), rfl⟩

/-- The coordinate homomorphism with codomain restricted to F_m. -/
def coordinates : Coordinates m →* F m hm :=
  (ambientCoordinates m hm).codRestrict (F m hm)
    (fun c => ambientCoordinates_range_le m hm ⟨c, rfl⟩)

@[simp]
theorem coordinates_coe (c : Coordinates m) :
    (coordinates m hm c : MatGroup m) = ambientCoordinates m hm c := rfl

@[simp]
theorem coordinates_generator (q : Fin m) :
    coordinates m hm (coordinateGenerator q) =
      (pi m hm).rangeRestrict (SelectionGroup.z (q.val : ℤ)) := by
  apply Subtype.ext
  exact ambientCoordinates_generator m hm q

theorem coordinates_injective : Function.Injective (coordinates m hm) := by
  intro a b hab
  apply ambientCoordinates_injective m hm
  exact congrArg Subtype.val hab

/-- The subgroup Z_m generated by the first m central involution images in F_m. -/
def Z : Subgroup (F m hm) :=
  Subgroup.closure (Set.range (fun q : Fin m =>
    (pi m hm).rangeRestrict (SelectionGroup.z (q.val : ℤ))))

/-- The coordinates cover exactly the subgroup generated in the report. -/
theorem coordinates_range : (coordinates m hm).range = Z m hm := by
  rw [range_eq_closure_coordinates]
  simp only [coordinates_generator, Z]

/-- Proposition 5.14: the specified subgroup is an elementary abelian group
of rank m. -/
def centerEquiv : Coordinates m ≃* Z m hm :=
  (MonoidHom.ofInjective (coordinates_injective m hm)).trans
    (MulEquiv.subgroupCongr (coordinates_range m hm))

/-- The explicit isomorphism sends each coordinate generator to pi_m(z_q). -/
@[simp]
theorem centerEquiv_generator (q : Fin m) :
    (centerEquiv m hm (coordinateGenerator q) : F m hm) =
      (pi m hm).rangeRestrict (SelectionGroup.z (q.val : ℤ)) :=
  coordinates_generator m hm q

/-- Every image of a central involution is central in F_m. -/
theorem z_image_mem_center (N : ℤ) :
    (pi m hm).rangeRestrict (SelectionGroup.z N) ∈ Subgroup.center (F m hm) :=
  z_mem_center_range (pi m hm) N

/-- The whole subgroup Z_m is contained in the centre of F_m. -/
theorem Z_le_center : Z m hm ≤ Subgroup.center (F m hm) := by
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨q, rfl⟩
  exact z_image_mem_center m hm (q.val : ℤ)

end FindimCounterexample.FiniteQuotients
