/-
Copyright (c) 2026 The findim counterexample formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The findim counterexample formalisation contributors
-/
import FindimCounterexample.SelectionCentral
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.BigOperators.Finsupp.Basic
import Mathlib.Algebra.Group.TypeTags.Hom

/-!
# The direct-sum map into the centre

The central involutions define a homomorphism from the direct sum of copies
of `ZMod 2` into the additive form of the centre. Its multiplicative range
is precisely the subgroup generated by the involutions. Injectivity is
supplied by the finite quotients in `SelectionIndependence`.
-/

open scoped IsMulCommutative

namespace FindimCounterexample.SelectionGroup

noncomputable section

/-- The central involution z_N, as an element of the centre. -/
def zCentral (N : ℤ) : Subgroup.center G := ⟨z N, z_mem_center N⟩

@[simp] theorem zCentral_coe (N : ℤ) : (zCentral N : G) = z N := rfl

/-- The cyclic additive map generated by the central involution z_N. -/
def cyclic (N : ℤ) : ZMod 2 →+ Additive (Subgroup.center G) :=
  ZMod.lift 2 ⟨zmultiplesHom _ (Additive.ofMul (zCentral N)), by
    change (2 : ℤ) • Additive.ofMul (zCentral N) = 0
    rw [two_zsmul]
    apply Additive.toMul.injective
    apply Subtype.ext
    exact (pow_two (z N)).symm.trans (z_sq N)⟩

/-- The generator of Z/2 maps to z_N. -/
@[simp] theorem cyclic_one (N : ℤ) : cyclic N 1 = Additive.ofMul (zCentral N) := by
  change ZMod.lift 2 _ ((1 : ℤ) : ZMod 2) = _
  rw [ZMod.lift_coe, zmultiplesHom_apply, one_zsmul]

/-- The additive direct-sum map of Corollary 5.15. -/
def centralSum : (ℤ →₀ ZMod 2) →+ Additive (Subgroup.center G) :=
  Finsupp.liftAddHom cyclic

@[simp] theorem centralSum_single (N : ℤ) (a : ZMod 2) :
    centralSum (Finsupp.single N a) = cyclic N a :=
  Finsupp.liftAddHom_apply_single _ _ _

@[simp] theorem centralSum_single_one (N : ℤ) :
    centralSum (Finsupp.single N 1) = Additive.ofMul (zCentral N) := by
  rw [centralSum_single, cyclic_one]

/-- The multiplicative form of the direct-sum map. -/
def centralProduct : Multiplicative (ℤ →₀ ZMod 2) →* Subgroup.center G :=
  centralSum.toMultiplicativeLeft

@[simp] theorem centralProduct_apply (f : Multiplicative (ℤ →₀ ZMod 2)) :
    centralProduct f = (centralSum f.toAdd).toMul := rfl

@[simp] theorem centralProduct_single_one (N : ℤ) :
    centralProduct (Multiplicative.ofAdd (Finsupp.single N 1)) = zCentral N := by
  simp

/-- The subgroup of the centre generated by all z_N. -/
def centralSubgroup : Subgroup (Subgroup.center G) := Subgroup.closure (Set.range zCentral)

private theorem zmod_two_cases : ∀ a : ZMod 2, a = 0 ∨ a = 1 := by
  decide

private theorem centralSum_mem (f : ℤ →₀ ZMod 2) :
    (centralSum f).toMul ∈ centralSubgroup := by
  induction f using Finsupp.induction with
  | zero => simpa only [map_zero, toMul_zero] using centralSubgroup.one_mem
  | @single_add N a f _ _ ih =>
    rw [map_add, toMul_add]
    apply centralSubgroup.mul_mem _ ih
    rcases zmod_two_cases a with ha | ha
    · simp [ha]
    · rw [ha, centralSum_single_one]
      exact Subgroup.subset_closure ⟨N, rfl⟩

/-- The direct-sum map covers exactly the subgroup generated by the z_N. -/
theorem centralProduct_range : centralProduct.range = centralSubgroup := by
  apply le_antisymm
  · rintro _ ⟨f, rfl⟩
    exact centralSum_mem f.toAdd
  · change Subgroup.closure (Set.range zCentral) ≤ centralProduct.range
    rw [Subgroup.closure_le]
    rintro _ ⟨N, rfl⟩
    exact ⟨Multiplicative.ofAdd (Finsupp.single N 1), centralProduct_single_one N⟩

/-- The subgroup defined inside the centre maps to the expected subgroup of G. -/
theorem centralSubgroup_map :
    centralSubgroup.map (Subgroup.center G).subtype = Subgroup.closure (Set.range z) := by
  rw [centralSubgroup, MonoidHom.map_closure, ← Set.range_comp']
  rfl

end

end FindimCounterexample.SelectionGroup
